### ISSUE TITLE
"content" should be in HTML format

### ISSUE THREAD

**Issue by syobocat** [totegamma/ccworld-ap-bridge#10]
Mastodon, Pleromaを始めとした多くのActivityPub実装は`content`フィールドの値をHTMLとして解釈します。
一方、Misskeyとそのフォークは`_misskey_content`フィールドがあればそちらの、なければ`content`フィールドの中身をMFMとして解釈します。

よって、現状配送しているMarkdown形式のテキストは`_misskey_content`フィールドに入れ、これをHTMLに変換したものを`content`フィールドに入れるのがより良い挙動と思います。

**Comment by totegamma** [comment]
https://github.com/concrnt/ccworld-ap-bridge/releases/tag/v0.3.0 で修正したのでCloseします

(このレポジトリは新しくconcrnt/ccworld-ap-bridgeに移動したのですが、オーナーが変わってしまったのでtransfer issueできず... 無念)
